// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableAutoStart():Promise<void>;

export function EnableAutoStart():Promise<void>;

export function Loginyzu():Promise<void>;

export function ReadData():Promise<{[key: string]: string}>;

export function SaveValue(arg1:{[key: string]: string}):Promise<void>;
