// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableAutoStart() {
  return window['go']['main']['App']['DisableAutoStart']();
}

export function EnableAutoStart() {
  return window['go']['main']['App']['EnableAutoStart']();
}

export function LoginWithAdvancedOptions(arg1, arg2) {
  return window['go']['main']['App']['LoginWithAdvancedOptions'](arg1, arg2);
}

export function Loginyzu() {
  return window['go']['main']['App']['Loginyzu']();
}

export function ReadData() {
  return window['go']['main']['App']['ReadData']();
}

export function SaveValue(arg1) {
  return window['go']['main']['App']['SaveValue'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
